on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      ### ⬇️ TESTES DO BACKEND
      - name: Instalar dependências backend
        working-directory: ./backend
        run: yarn

      - name: Rodar testes do backend
        working-directory: ./backend
        env:
          MONGO_URL: mongodb://localhost:27017/homemanager_test
          CI: true
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: yarn test

      ### ⬇️ FRONTEND: TESTES, BUILD E DEPLOY
      - name: Instalar dependências
        working-directory: ./frontend
        run: yarn

      - name: Rodar testes E2E
        working-directory: ./frontend
        run: yarn test:ci
        env:
          VITE_API_URL: https://home-manager-q581.onrender.com

      - name: Build (modo produção)
        working-directory: ./frontend
        run: yarn build-prod && cp dist/index.html dist/404.html
        env:
          VITE_API_URL: https://home-manager-q581.onrender.com

      - name: Deploy no gh-pages/masters
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          publish_dir:    frontend/dist
          publish_branch: gh-pages
          destination_dir: master